### ISSUE TITLE
Don't hardcode the whitelist.

### ISSUE THREAD

**Issue by d4rken** [TheRedSpy15/LTECleanerFOSS#10]
https://github.com/TheRedSpy15/LTECleanerFOSS/blob/7de6b81f772dfaf1c77437b4f7de51e382411202/app/src/main/java/theredspy15/ltecleanerfoss/MainActivity.java#L220

Not all devices use `/storage/emulated/0` as internal storage path, e.g. some have `/storage/sdcard0`. Use `Environment.getExternalStorageDirectory()` within your whitelist too.

**Comment by TheRedSpy15** [comment]
I just pushed a commit addressing this

Let me know if it`s what you suggested

**Comment by d4rken** [comment]
5fa65df16ab3448fac7e00de78c340c7584aee8b will work.

If we are aiming for perfect we could go further:

* Instead of using `toString()` use `getPath()` or `getAbsolutePath()` in case the `toString()` representation ever changes.
* Instead of `.add(Environment.getExternalStorageDirectory().toString() + "/Music")` use `new File(Environment.getExternalStorageDirectory(), "Music").getPath()` such that the `File` constructor handles the path separators.

**Comment by TheRedSpy15** [comment]
Closing this because I`m assuming I implemented it correctly

**Comment by d4rken** [comment]
Sorry didn't notice the commit. Yes you did. 👍

**Comment by d4rken** [comment]
On a side note, I think advertising with

> An alternative to SD Maid, and one that is completely free and open source!

is dishonest, maybe think about improving the description @TheRedSpy15
