### ISSUE TITLE
Lte

### ISSUE THREAD

**Issue by Dabe11** [TheRedSpy15/LTECleanerFOSS#103]
Description:
---

What is the meaning of LTE

Device info:
---
<table>
<tr><td>App version</td><td>4.1.0</td></tr>
<tr><td>App version code</td><td>36</td></tr>
<tr><td>Android build version</td><td>33517</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>OPM2.171019.012 release-keys</td></tr>
<tr><td>Device brand</td><td>Cloudfone</td></tr>
<tr><td>Device manufacturer</td><td>Cloudfone</td></tr>
<tr><td>Device name</td><td>Go_Connect_Lite_2</td></tr>
<tr><td>Device model</td><td>Go Connect Lite 2</td></tr>
<tr><td>Device product name</td><td>Go_Connect_Lite_2</td></tr>
<tr><td>Device hardware name</td><td>k101</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
"Logs Temporary and Empty"

To describe the when the app cleaned when it was first created. It also makes the app "sound fast"
