### ISSUE TITLE
Scan mode/button

### ISSUE THREAD

**Issue by gsantner** [TheRedSpy15/LTECleanerFOSS#11]
Currently there is only the option delete stuff. I would like to know what exactly will get deleted. Could a "Scan" only button be added which shows a list of to be deleted files?

**Comment by TheRedSpy15** [comment]
Yes, I will definitely add that some time soon

It was actually planned, but forgotten about when I started another project

**Comment by TheRedSpy15** [comment]
Hopefully will have an update ready today or tomorrow

**Comment by M1Aston** [comment]
Perhaps also show how much space was freed up?

**Comment by TheRedSpy15** [comment]
@M1Aston

Already working on this from issue #13

**Comment by TheRedSpy15** [comment]
An update is being published with an analyze option
