### ISSUE TITLE
007

### ISSUE THREAD

**Issue by Samboy1990** [TheRedSpy15/LTECleanerFOSS#110]
Description:
---

من اصلا دقیق نمیدونم این اپ برای چه کاره و به چه درد میخوره.
یه نفر که میدونه کمکم کنه لطفا...

Device info:
---
<table>
<tr><td>App version</td><td>4.1.0</td></tr>
<tr><td>App version code</td><td>36</td></tr>
<tr><td>Android build version</td><td>J500HXXS2BRI2</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.J500HXXS2BRI2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j53g</td></tr>
<tr><td>Device model</td><td>SM-J500H</td></tr>
<tr><td>Device product name</td><td>j53gxx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
Hello! The app is simply meant to remove safe to delete files on your phone. To free up more space and increase privacy
