### ISSUE TITLE
Separate and outline "Analyze" and "Clean" buttons

### ISSUE THREAD

**Issue by DuMuT6p** [TheRedSpy15/LTECleanerFOSS#113]
**Is your feature request related to a problem? Please describe.**
When selecting "Clean" a pop-up appears with button "Analyze" and "Clean". As they are only text and right next to each other people can missclick.

**Describe the solution you'd like**
Have an outline for each button. Also move "Analyze" to the bottom left corner of the pop-up so they can be further appart.

P.S. Thank you for developing this app.

**Comment by TheRedSpy15** [comment]
I will be looking into solutions for this. At this moment I would like to minimize the number of buttons on the screen since the number one issue a while back ago was the app not properly supporting different screen sizes (especially super small ones).

I do have some ideas how ever

**Comment by LongJohn-Silver** [comment]
@TheRedSpy15 IMO having two buttons wont use much space even in small screens. Maybe they could become smaller if the screen is smaller, or to have one on top of each other, although this wouldn't look good as the default for normal/big screens.

**Comment by TheRedSpy15** [comment]
maybe a couple days from release: f6c5e0837b4ed1afab6ec7986c57d188514c3ec5
