### ISSUE TITLE
Caches cleaner

### ISSUE THREAD

**Issue by SamraMehboob** [TheRedSpy15/LTECleanerFOSS#114]
Hello there!
The descriptions mentions that it has the feature to clear caches. But I guess it doesn't work. Please add this feature as well.
It might be possible by using accessibility service because most of the classes and permissions like CLEAR CACHE are deprecated after API level 22.
 And thank you for this great source. It really proved helpful :)

**Comment by TheRedSpy15** [comment]
Hello! Caches in the description refer to folders labelled as caches and are exposed by other apps. I will look into using accessibility service to access caches that are not exposed.

**Comment by TheRedSpy15** [comment]
#146
