### ISSUE TITLE
Possible bug or failures

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#116]
Good afternoon @TheRedSpy15 

First of all thank you very much for its great application and for all your effort and effort you put into it. And thank you very much for sharing it with us. I also take this opportunity to comment on some possible flaws that I found in this latest version. It turns out that in the latest version of Lineageos with Magisk also in its latest version. I noticed that it doesn't clean up the recent files that come out in the file browser of lineageos. Or some temporary files that can be seen with Amaze from fdroid. I also noticed that it also does not clear the cache of the applications you have used. I don't know if it could be done for Lte to clean it? I also noticed that it shows in the report that it shows while it is cleaning. Which cleans gallery files. But if in the file explorer you put show hidden files. There you will find those files.

 I hope this report or topic does not take me badly. And I hope to be of great help to you in making Lte what it is, a GREAT APP. 

Receive a warm hug and thank you very much for your time.

**Comment by TheRedSpy15** [comment]
Hello! Do you have an sd card? Chances are the files are on that, and LTE Cleaner does not current (but will soon!) scan sd cards

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for your help and time.

I don't have sd on my cell phone. Nor can you stand it.

But for example applications that do not clean:

Adaway

Fdroid

Gallery

Archives

Etc...

I use lineage with the latest version of Magisk.

A hug

**Comment by gallegonovato** [comment]
Good afternoon @TheRedSpy15 



I would also like to inform you that Lte does not clean the cache of:



Newpipe

Youtube Vanced



And that it doesn't erase the clipboard either with Pure Android or Lineageos



Nor on Samsung s9, s9+, nexus 6p.



A hug

**Comment by TheRedSpy15** [comment]
Hello @gallegonovato

What settings in the app do you have enabled?

**Comment by gallegonovato** [comment]
Good morning @TheRedSpy15 


https://ibb.co/vcSFxL0
https://ibb.co/30Cyy4r

A hug

**Comment by gallegonovato** [comment]
Good afternoon:



I found this application on fdroid: https://f-droid.org/en/packages/io.github.deweyreed.clipboardcleaner/ 

 

I wanted to make a suggestion that I hope won't be taken the wrong way.  I don't know if the creator of that other application could help improve Lte Cleaner



A hug

**Comment by TheRedSpy15** [comment]
I have decided to revisit working on LTE Cleaner after life getting in the way for a few months. But I realized you are not using android per say. And I will not be providing support for lineageOS first hand. If someone else wants to take over, by all means! But I personally will not be working on support for this.
