### ISSUE TITLE
Include MIUI's wlan logs 

### ISSUE THREAD

**Issue by AzimsTech** [TheRedSpy15/LTECleanerFOSS#117]
Description:
---

Please Include /sdcard/wlan_logs directory into the list.

Device info:
---
<table>
<tr><td>App version</td><td>4.1.0</td></tr>
<tr><td>App version code</td><td>36</td></tr>
<tr><td>Android build version</td><td>V8.5.7.0.MCCMIED</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>rolex</td></tr>
<tr><td>Device model</td><td>Redmi 4A</td></tr>
<tr><td>Device product name</td><td>rolex</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
Hello! This would be included already, if it wasn't on the sd card. The app currently does not scan the sd card. This is the highest priority feature at the moment and will be added soon!

**Comment by TheRedSpy15** [comment]
closing this since it is just needing sd card scanning which is being worked on #14
