### ISSUE TITLE
detection complete?

### ISSUE THREAD

**Issue by M1Aston** [TheRedSpy15/LTECleanerFOSS#12]
Unlike LTE Cleaner, and some other cleaners I have tried, an app called Android Cleaner also detects\deletes cached files by NewPipe (a YouTube player).  Is it necessary to do this? I don't know, but I do find it useful AND of course it is completely safe to delete downloaded\cached video stuff (and other apps\similar stuff that is not detected yet?)

**Comment by TheRedSpy15** [comment]
I would love to have LTE Cleaner delete NewPipe cached files (I use it too). Unfortunately, there isn't a publicly known way of doing so in newer versions of android.

A few apps have managed to find a way, but don't say how.

Currently the only way is on rooted Devices

**Comment by M1Aston** [comment]
Thanks for the reply.
I don't think that's right. 
Systweak Android Cleaner works (talking about the NewPipe cache) on my non-rooted Device.
It reports it deleted the cached files, and after checking I can confirm they are gone.

**Comment by M1Aston** [comment]
Oops, I overlooked ""A few apps have managed to find a way, but don't say how"".
Forget about my previous post.

**Comment by TheRedSpy15** [comment]
I have added an experimental cache filter to the latest release (currently still being published), will be trying to find a way to delete other app caches

**Comment by M1Aston** [comment]
Thank you. I'll give it a go as soon as the update is available.

**Comment by TheRedSpy15** [comment]
I just got a build working that manages to wipe out the NewPipe cache completely. I'm still working on a system to wipe out the cache completely for other apps

**Comment by M1Aston** [comment]
That's really great.
Unfortunately F-Droid didn't update yet. 
But I see a newer Play Store version is available. I'll get that one instead and give it a try.
Thanks for the quick update(s).

**Comment by TheRedSpy15** [comment]
Yah, unfortunately I'm still new to distributing apps on Fdroid. So it might be a little while to that one gets an update, hopefully at most a week

**Comment by TheRedSpy15** [comment]
I got a beta build on that you can try out that is the first attempt at being able to clear other app caches

link: https://github.com/TheRedSpy15/LTECleanerFOSS/releases/tag/3.0.0-beta

**Comment by M1Aston** [comment]
I don't really know how to test it, but the NewPipe cached files have vanished. Can't see them and neither can (soon to be uninstalled) Android Cleaner. :-)
After running LTE, the only thing Android Cleaner found were two several days old files in storage/emulated/0/recovery, called ""status"" and ""shortreport"". One of them is a log\txt file and the other I couln't open, but I'm guessing it is safe to delete those items.
