### ISSUE TITLE
"Aggressive Filter" information/explanation? 

### ISSUE THREAD

**Issue by nullled** [TheRedSpy15/LTECleanerFOSS#122]
I've been using this app for a very long time and am a huge fan of it. 
The only issue I have is that I can't seem to find any explanation of the "Aggressive Filter", other than the rather unhelpful little subheading that says "Too much to list here".

It really should be explained within the app description on F-Droid, the Play Store, and in the readme, in my opinion, but I would be satisfied if you could explain what evening the aggressive filter does exactly, and maybe some precautionary notes.

Any information on this feature would be greatly appreciated! 

Thank you very much for your time and amazing work! With this feature explained, I'll be happy to buy Pro immediately after :)

    

———————

Regards,
nullled

**Comment by TheRedSpy15** [comment]
Hello! Agressive filter is as follows:

        supersonicads
        Cache
        Analytics
        thumbnails?
        mobvista
        UnityAdsVideoCache
        albumthumbs?
        LOST.DIR
        .Trash
        desktop.ini
        leakcanary
        .DS_Store
        .spotlight-V100
        fseventsd
        Bugreport
        .Trash
        cache
        .exo
        thumbs?.db

I will be adding it to F-Droid and the play store's description

**Comment by nullled** [comment]
Thanks for explaining this!
I love the app and have recommended it to many others. Keep up the great work!
