### ISSUE TITLE
Show Cleaning Completed instead of showing directories

### ISSUE THREAD

**Issue by jerryn70** [TheRedSpy15/LTECleanerFOSS#13]
After completing the cleaning process show "cleaning completed". And show total size of cleaned

**Comment by TheRedSpy15** [comment]
Will be adding this to the to do list for the next update

**Comment by TheRedSpy15** [comment]
I originally had a toast saying cleaning complete, but decided only having a toast showing amount of space freed

**Comment by TheRedSpy15** [comment]
Just put out an update with a toast showing the amount free
