### ISSUE TITLE
Why only update on Google?

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#131]
Good afternoon:

I am contacting you, first thanking you for your effort and application. 

My question is because the new version of your application is only available in the Google Play Store.

Me for example, and I imagine that many more people do not use this shop. And we download the applications from Fdroid or from the creator's github itself.

What is strange is that the new version is not even his github.

This means that there will be no more applications on your github or fdroid?

A hug and thanks for your time.

**Comment by gallegonovato** [comment]
Good afternoon: Thank you very much for your application. I would just like to ask if you will upload the updates to github or fdroid. Or those of us who don't use the google play store run out of more updates. A hug and a thousand thanks for your help and time and patience

**Comment by TheRedSpy15** [comment]
Update for F-Droid is now being processed

**Comment by Krawei** [comment]
The Problem with different versions occurs again. Can you please update the app on FDroid again? Thank you 😃.
