### ISSUE TITLE
Make the UI available in "Landscape" mode

### ISSUE THREAD

**Issue by AdamKane41** [TheRedSpy15/LTECleanerFOSS#133]
**When using an Android machine in "Landscape" mode, when opening "LTE Cleaner" the screen flips into "Portrait" mode for it's UI. Once done using the app, when quiting it again rotate back into the previous orientation.**

- This behaviour makes the operations okward to achieve and can provoke some unintentional clicks (or taps) on sensitive options.

**I once modified this app (to learn, and for fun!🐙) and discovered that "Allowing" an Android app to be displayed in "Landscape" mode (If the OS is in "Auto-Rotate" or "Landscape" mode) the code only needs a minor change in one file... From memory it looked like "ALLOW LANDSCAPE=0"... Either a 1/0 or YES/NO switch. I'm pretty sure you know exactly wich Files and Line I'm referring to...**

- The "LTE Cleaner" app should support both screen orientations, the Standard "Portrait" mode as well as the "Landscape" one. (Auto rotate the UI)

**Using a "Force/Lock Screen Orientation" app displays the UI of LTE Cleaner in the position consistent with the rest of the system without "flipping" back and forth.**

- This 3rd party app can be enabled system wide permanently or, as I currently use, manually toggled before and after using "Portrait-Only" apps. There are countless available apps able to achieve this work around, both as stand alone apps or part of multi tools/tweaks apps. My go-to app for this is "Power Toggles" ( _com.painless.pc_ ).

**Screenshots of what LTE Cleaner looks like in Landscape mode on an Android phone!**
---
![4-Screenshot_2020-09-13-19-35-00](https://user-images.githubusercontent.com/30092603/93032525-115d9500-f600-11ea-9717-5671337f8004.png)
---
![3-Screenshot_2020-09-13-19-40-23](https://user-images.githubusercontent.com/30092603/93032526-11f62b80-f600-11ea-99e4-3a62e1103429.png)
---
![2-Screenshot_2020-09-13-19-33-29](https://user-images.githubusercontent.com/30092603/93032527-11f62b80-f600-11ea-8f85-6c2ecdf74872.png)
---
![1-Screenshot_2020-09-13-19-37-44](https://user-images.githubusercontent.com/30092603/93032528-128ec200-f600-11ea-91e1-d7534d56a5fc.png)
---
Thanks, sorry if duplicate request, 
**Peace**!

**Comment by AdamKane41** [comment]
Sorry for the brain-fart... The File and Line Code I was mentioning are:

**AndroidManifest.xml**

And maybe something like:

**android:screenOrientation="fullSensor"** 
or
 **android:screenOrientation="unspecified"**

Would that make the app behave the way I expect?
**Peace**

**Comment by TheRedSpy15** [comment]
This wouldn't be ideal more most users. And elders could be thrown off by it. I don't think this is a good fit for LTE Cleaner. Hence me manually disabling it in the first place
