### ISSUE TITLE
Crash on Android 11

### ISSUE THREAD

**Issue by woodruffandtheschnibbleofazimuth** [TheRedSpy15/LTECleanerFOSS#153]
Hello,
ad title said it does not work on Android 11.
It remains at 0% and crash.

**Comment by TheRedSpy15** [comment]
Unfortunately google play store is making releasing the fix kind of a pain

The issue and fix is known. Just working on a way to push it

**Comment by woodruffandtheschnibbleofazimuth** [comment]
> Unfortunately google play store is making releasing the fix kind of a pain
> 
> The issue and fix is known. Just working on a way to push it

Thank you :)

**Comment by felschr** [comment]
What about F-Droid? The last update there is from 2020-02-26.

**Comment by NSTAdventure** [comment]
> What about F-Droid? The last update there is from 2020-02-26.

I don't know why dev ignore f-droid version they upload newer version on playstore which i not use it 

I had to de google my android start my new journey without google

**Comment by DrDustwolf** [comment]
Version 4.1.0. from F-Droid chrashes on LineageOS 18.1 (ANDROID 11) on a Lenovo Yoga Tab 3 Plus LTE (YT-X703L).

**Comment by DrDustwolf** [comment]
Version 4.2.1. directly from github also chrases.

**Comment by TPS** [comment]
Problem & solution might be @ #171.

**Comment by TheRedSpy15** [comment]
Fix created and coming
