### ISSUE TITLE
Auto clear apps system cache

### ISSUE THREAD

**Issue by NSTAdventure** [TheRedSpy15/LTECleanerFOSS#158]
**Is your feature request related to a problem? Please describe.**
Ok this app clearing empty folder and cache but the only one thing that annoy me is app system cache is not cleaned :-( 

**Describe the solution you'd like**
I want you add new feature to clean cache from app

**Describe alternatives you've considered**
No Alternative

**Additional context**
System app cache?

See SS:
![Screenshot_2021-02-03-07-06-58-15](https://user-images.githubusercontent.com/50813528/106679055-75541a80-65ee-11eb-8dbf-a7a91a866400.jpg)

In Indonesian Mean Bersihkan Cache
In English Mean Clear Cache 
I mean this one app not clear this cache when i use it

**Comment by NSTAdventure** [comment]
@TheRedSpy15 I forgot to mention
auto clear system cache on app info like i'ven show the picture above need accessibility service permission in android Q

**Comment by yant0** [comment]
Would like to have this. wouldnt mind if its root only

**Comment by NSTAdventure** [comment]
> Would like to have this. wouldnt mind if its root only

Hey... Hey hey It can't be like that, not all Android users are already rooted adb or accessibility services is recommended too @TheRedSpy15

**Comment by TheRedSpy15** [comment]
> Would like to have this. wouldnt mind if its root only

There will be zero root only features in any future update

**Comment by yant0** [comment]
You said it in f-droid description that android marshmallow + wouldnt let apps clean other apps cache

**Comment by NSTAdventure** [comment]
> > Would like to have this. wouldnt mind if its root only
> 
> There will be zero root only features in any future update

What do u meant by zero root? @TheRedSpy15

**Comment by TheRedSpy15** [comment]
> > > Would like to have this. wouldnt mind if its root only
> > 
> > There will be zero root only features in any future update
> 
> What do u meant by zero root? @TheRedSpy15 

As in, no features that require a rooted device

**Comment by jerryn70** [comment]
Sd maid uses accessibility service to clean other apps cache and it working well . We also need that kind of feature. Waiting for the future update .

**Comment by TheRedSpy15** [comment]
refer to #146
