### ISSUE TITLE
Cleaning is not good need improvement

### ISSUE THREAD

**Issue by jerryn70** [TheRedSpy15/LTECleanerFOSS#16]
Hey, i compared this app with sd maid . 

1st i checked my OG youtube cache size, it is about 9.78mb . Then I cleaned everything use LTE app then checked the cache size of OG, now it is reduced to 9.77mb .

While using LTE app cache reduced from 9.78mb to 9.77mb

Then I cleaned everything using sd maid . 
Now the cache is reduced from 9.78mb to 5.45mb. 

From this we can say that sd maid is more powerful in cleaning.

I know this app in starting stage . Hope you will improve in upcoming updates . Always supporting FOSS app :smile:

**Comment by TheRedSpy15** [comment]
This is my number one priority right now. I have a beta build you can try that from my testing is able to free more space than SD Maid

link: https://github.com/TheRedSpy15/LTECleanerFOSS/releases/tag/3.0.0-beta

**Comment by jerryn70** [comment]
Tested with the default settings. There is no improvements . 
I'm afraid to use the aggressive filter and .exo filter because I'm testing this in my daily driver.

**Comment by jerryn70** [comment]
.exo file cleaning helped to clear the cache of ogyoutube .  
But aggressive filtering is dangerous. Because it will delete the TWRP backup files.

**Comment by jerryn70** [comment]
![](https://i.imgur.com/BadV8vR.png)

**Comment by TheRedSpy15** [comment]
I suggest white listing TWRP backup files

Also, I don't use that app, but I think those are safe to delete, they have cache in the name

**Comment by jerryn70** [comment]
If we delete that files restore will break

**Comment by TheRedSpy15** [comment]
@jerryn70  @M1Aston I will be releasing an update in the coming days the should vastly improve the cleaning process, as well as add automatic whitelisting

**Comment by M1Aston** [comment]
Great news. I can't wait to give it a go. 
The app seems to be doing a pretty good job as it is, but any improvements are welcome. :-)

**Comment by TheRedSpy15** [comment]
Just a little update. I haven't been able to work on the app as much as I wanted to (darn exams!), but will have the update out before the year ends

**Comment by M1Aston** [comment]
First things first. Good luck with your exams.
We can wait for an updated version. :-)

**Comment by TheRedSpy15** [comment]
Another update: I will be releasing the update tonight. It life and other projects kinda took over a little

**Comment by TheRedSpy15** [comment]
It may have taken a little bit longer than wanted, but the update is finally out

Let me know if the cleaning has improved, and don't forget to try out the new auto whitelist :)
