### ISSUE TITLE
You will continue with versions on github or fdroid

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#161]
Good afternoon:

First of all thank you for your application.

I wanted to ask you, if you allow me, taking or releasing new versions in your github and / or fdroid.

It would be a good option to continue releasing versions in your github as well. Not only in the google play store. So as to continue with the great trend of your great application.

That it is valid even for lineageos.

A hug and thanks for your attention

**Comment by TheRedSpy15** [comment]
The upcoming update will be released on Github and FDroid. Fdroid just takes a little time for it to process
