### ISSUE TITLE
Hi can I use these source code

### ISSUE THREAD

**Issue by safeeraliPS** [TheRedSpy15/LTECleanerFOSS#162]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LongJohn-Silver** [comment]
Not the owner of the repo but you can as long as you follow the terms and conditions of the project's license.

**Comment by TheRedSpy15** [comment]
Please read the following: https://www.gnu.org/licenses/gpl-3.0.en.html

it goes in detail about the license LTE Cleaner is under and its restrictions
