### ISSUE TITLE
Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [TheRedSpy15/LTECleanerFOSS#164]
Dear team,

when I take a look on google play store the current version is 4.2.1 in the F-Droid store the current version is 4.1.0

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by Krawei** [comment]
> Dear team,
> 
> when I take a look on google play store the current version is 4.2.1 in the F-Droid store the current version is 4.1.0
> 
> What's the reason for this gap? Is there a bug in the build process?
> 
> Please fix this.
> 
> Kind Regards,
> 
> Krawei

@TheRedSpy15 Is there any progress here?

**Comment by angelog0** [comment]
`4.2.1` is on F-Droid since 20210818 but it [does not](https://github.com/TheRedSpy15/LTECleanerFOSS/issues/171#issuecomment-864467802) work on android 11...

**Comment by TheRedSpy15** [comment]
Yah Fdroid is a pain. It missed the last update but it was a rather small one. I recommend github or play store. The next one is BIG and I will make sure fdroid gets it
