### ISSUE TITLE
Show screenshots in F-droid and Github readme

### ISSUE THREAD

**Issue by aha999** [TheRedSpy15/LTECleanerFOSS#168]
**Is your feature request related to a problem? Please describe.**
Currently, we can't see what the program looks like before installing it and to see the functions.

**Describe the solution you'd like**
Add screenshots to F-droid and Github readme.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by TheRedSpy15** [comment]
Already using  one on github. Eventually will use one for fdroid

**Comment by aha999** [comment]
You could add at least that one for starters

**Comment by TheRedSpy15** [comment]
should be added with: 43344598463061390c7abde7804f8582a5cd09b4

if not, I'll reopen this issue

But we'll have to wait till next update to test

**Comment by TheRedSpy15** [comment]
Thank you! Its still a WIP but it definitely is getting there
