### ISSUE TITLE
This app does not work on Android 11 because permissions

### ISSUE THREAD

**Issue by angelog0** [TheRedSpy15/LTECleanerFOSS#171]
I installed it (4.2.1) downloading the apk from apkpure (don't use Google services) and it worked until yesterday when there was the upgrade from Android 10 (?) to 11. Now LTE Cleaner has access to only multimedia files (jpg) so it cleans nothings. It should clean the apk files downloaded but because those permissions it ignores those files.

I wonder if there is some solution. 

[Someone](https://github.com/termux/termux-app/issues/2088) suggested to change AndroidManifest.xml but some try with other apk failed.

**Comment by TPS** [comment]
It needs permission "Allow management of all files" _not_ "Allow access to media only" which is why it's failing.  Per [the scoped storage documentation](https://developer.android.com/about/versions/11/privacy/storage), there're several steps to resolving this.

**Comment by angelog0** [comment]
I see now that `4.2.1` is on F-Droid (2021.06.18), but (at least on android 11)  it shows that

```
/storage/emulated/0/Android/.Trash
/storage/emulated/0/Android/.Trash/com.sec.android.app.myfiles
```

should be cleaned (8 KiB). But when it tries, it enters in a loop.. I have to close LTE Cleaner...

**Comment by TheRedSpy15** [comment]
A fix has been created and is in the next update

**Comment by angelog0** [comment]
Which is the fix? Which commit has it? Thanks.

**Comment by TheRedSpy15** [comment]
> Which is the fix? Which commit has it? Thanks.

Amongst one of the recent ones I committed. I am currently committing a lot at once until I release the update

Just required asking the user for an additional permission

**Comment by angelog0** [comment]
>  I am currently committing a lot at once 

This is the reason for which I asked... It is hard to find the right commit for that issue..

**Comment by TheRedSpy15** [comment]
> > I am currently committing a lot at once
> 
> This is the reason for which I asked... It is hard to find the right commit for that issue..

Yahhh I'm not even sure which one it is. With school and moving between states right now. I'm using git as more of a save everything all together at the end of the day thing. And not using useful name for the commits. Once I release this update, I will go back to using git the way I should
