### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by TheRedSpy15** [TheRedSpy15/LTECleanerFOSS#18]
Since its the most spoken language in the world, I feel its rather important to have support for in the app

An easy way of helping translate is using the app called "stringlate" on F-Droid

**Edit**: Chinese simplified still needs to be added

**Comment by TheRedSpy15** [comment]
Thanks to @cges30901 !

**Comment by cges30901** [comment]
I only translated into Traditional Chinese, but more people use Simplified Chinese. So only people in Taiwan can see the translation.

**Comment by TheRedSpy15** [comment]
@declare2006 sorry for the late response

I suggest using an app call stringlate on fdroid

Makes the whole process extremely quick and easy

**Comment by TheRedSpy15** [comment]
@declare2006 not exactly, I'm to use stringlate as it makes translating and creating a pull request straight forward

It makes it so you simply have to enter the translated text and you github account, then it will open a pull request for you
