### ISSUE TITLE
Make Suggestion does not work

### ISSUE THREAD

**Issue by TheLastProject** [TheRedSpy15/LTECleanerFOSS#180]
**Describe the bug**
Trying to create a suggestion from the app fails with an invalid access token message.

**To Reproduce**
1. Go to Settings
2. Click on Make Suggestion
3. Fill in the field

**Expected behavior**
Expected it to work.

**Screenshots**
![Screenshot_20210725-011050_LTE_Cleaner](https://user-images.githubusercontent.com/1885159/126883104-d3b429d4-b9a6-4894-92ea-121dd5cb97fe.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 -  OS: Lineage for microG 17.1 (Android 10)
 - Version 4.2.1 from F-Droid

**Comment by TheRedSpy15** [comment]
Feature being removed in upcoming  update, so bot account was closed and the dependency used for such feature has been shutdown effectively
