### ISSUE TITLE
Progress bar goes multiple times to 100%

### ISSUE THREAD

**Issue by fleaz** [TheRedSpy15/LTECleanerFOSS#188]
**Describe the bug**
When running a "clean" job, the progress bar goes up to 100%, then jumps back to some random value around 60-80, goes back up again to 100, jumps back down, etc etc. This happens multiple times until the run is  finished. When only running "analyze" this doesn't happen.

**To Reproduce**
1. Click on clean
2. Watch the progress bar go up to 100 multiple times

**Expected behavior**
The progress bar should go up to 100% only once :D

**Smartphone:**
 - OS: Android 10, Patchlevel September 2020
 - Phone: OnePlus 5t

**Additional context**

**Comment by TheRedSpy15** [comment]
I agree it is confusing, and I will address it. But it does run multiple times (with a maximum limit). Each time it finds something, it runs once more, since some files seemingly hide in the first run (honestly not sure why)
