### ISSUE TITLE
Some thumbnail and cache files are not detecting

### ISSUE THREAD

**Issue by jerryn70** [TheRedSpy15/LTECleanerFOSS#189]
Some thumbnail files and cache folders are not detecting. Thumbnail ending with extensions like 
Filename.thumb0
Filename.thumb1
Filename.thumb2 ...etc going....
In my device i can see upto filename.thumb12 .

And some cache folder that are named .cache are also not detecting .

**Comment by TheRedSpy15** [comment]
I just released a new update, give that a try and let me know if it isn't removing those. What android version are you on as well?

**Comment by jerryn70** [comment]
@TheRedSpy15 sure, im waiting for the fdroid to publish the update. My android version is 10

**Comment by TheRedSpy15** [comment]
fdroid has been updated (finally), any changes?

**Comment by jerryn70** [comment]
@TheRedSpy15 sorry, no changes.

**Comment by jerryn70** [comment]
File location
MIUI > video > thumbsmall

**Comment by TheRedSpy15** [comment]
On the playstore branch, waiting for translations to be added to master and I'll add it to the master branch. Then push the update hopefully tomorrow
