### ISSUE TITLE
[FR] Removal of the internet permission.

### ISSUE THREAD

**Issue by KanadeTachibana2** [TheRedSpy15/LTECleanerFOSS#191]
**Is your feature request related to a problem? Please describe.**

"LTE Cleaner" no longer has the option to report issues to "GitHub" through the app itself, so the logical path here would be completely removing the internet permission.

**Describe the solution you'd like.**

Getting rid of the now unnecessary internet permission.

**Describe alternatives you've considered.**

Using the app without being connected to Wi-Fi?

**Additional context.**

.

**Comment by TheRedSpy15** [comment]
thanks for the reminder actually!
