### ISSUE TITLE
The new version will be uploaded to fdroid?

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#193]
Good afternoon:

I thank you for continuing to create new versions of this superb application.

I would like to ask you a question if I may. Will you upload this latest version to fdroid.

Best regards

**Comment by TheRedSpy15** [comment]
Fdroid should be automatically processing the update right now, it just takes a few days

**Comment by angelog0** [comment]
Sure this version works? I installed it on android-11 from the [apk](https://github.com/TheRedSpy15/LTECleanerFOSS/releases/download/4.5.0/LTE.Cleaner.apk) but it cleans almost nothing, just the apks (I allowed for permissions on **ALL** files). This device with android-11 does not have other cleaner tools, so one would expect a lot of things to be cleaned. On the other way, the 4.2.1 version on another device, with Android-8, on which i run it regularly, each time has a lot of things to clean...

I wonder if this could depend on the previous not working installation of LTE Cleaner on that device with android-11.. How could I install this new version in a clean way? Are there directories and/or files to be removed before the new installation? (Sometimes I had installed from fdroid and sometimes I installed from your apks... )

**Comment by gallegonovato** [comment]
> Sure this version works? I installed it on android-11 from the [apk](https://github.com/TheRedSpy15/LTECleanerFOSS/releases/download/4.5.0/LTE.Cleaner.apk) but it cleans almost nothing, just the apks (I allowed for permissions on **ALL** files). This device with android-11 does not have other cleaner tools, so one would expect a lot of things to be cleaned. On the other way, the 4.2.1 version on another device, with Android-8, on which i run it regularly, each time has a lot of things to clean...
> 
> I wonder if this could depend on the previous not working installation of LTE Cleaner on that device with android-11.. How could I install this new version in a clean way? Are there directories and/or files to be removed before the new installation? (Sometimes I had installed from fdroid and sometimes I installed from your apks... )

Buenas tardes: Check in lte settings, whitelisted if you have anything in it. And if so, try deleting what you get on the white list. Also check in the settings to have all the boxes that come out to be marked checked. That is: enable generic filter, etc ... Also if you want you can try to uninstall the version you have of lte on your mobile. Restart the mobile, and reinstall the latest version. And review the lte settings, checking all the boxes. In Android 11 I can not tell you, but in lower Android at the moment very well. A hug

Pd: You have the latest version of the app at https://github.com/TheRedSpy15/LTECleanerFOSS/releases

**Comment by angelog0** [comment]
@gallegonovato, re-read my post. I have the latest LTE Cleaner (4.5.0) and the issue I flagged is with android 11 not with _lower Android_. Obviously, in the settings **ALL** the boxes are checked!

**Comment by TheRedSpy15** [comment]
@angelog0 unfortunately in with android 11 less files are exposed, and you'll find that many of the exposed ones are already removed from the previous version of the app. There is a work around that I will be adding but it may take a week or two

this past update was simply to prevent the app from working entirely on android 11

**Comment by TheRedSpy15** [comment]
it seems the build failed on fdroid. I will be looking into this. For now you might just want to download directly from github if you don't want to use the play store

**Comment by gallegonovato** [comment]
Good evening @TheRedSpy15

What I did notice in the latest version. That if in settings, you have Auto Whitelist checked. Every time you scan and clean. Or already directly you have clean.

It fills the whitelist. With the same addresses or paths of the files to keep. Repeating the paths and so on again and again. And always the same with each scan and clean. 

In the previous version this did not happen. I imagine that this is done in case there are new changes or new applications and others on the mobile. But it always fills the whitelist with the same thing. And in the previous version also checked the changes and so on but did not do this in the whitelist.

And thanks a lot for the notice of what happened with the app on fdroid. 

A hug and thanks for your time

**Comment by TheRedSpy15** [comment]
@gallegonovato hmm I'll look into it, sounds like a simple fix

**Comment by OliverLew** [comment]
F-droid updated

**Comment by angelog0** [comment]
Now I installed 4.5 from F-droid with the same results on **android 11**: with permissions to **ALL** files and all checked in Settings it has deleted only the apk needed for its installation....

**Comment by gallegonovato** [comment]
> Now I installed 4.5 from F-droid with the same results on **android 11**: with permissions to **ALL** files and all checked in Settings it has deleted only the apk needed for its installation....

Good afternoon

Wait for TheRedSpy15 to release a new version. I say this because of what I tell you in a previous answer:

https://github.com/TheRedSpy15/LTECleanerFOSS/issues/193#issuecomment-913334007

A hug

**Comment by TheRedSpy15** [comment]
Closing this since the original issue was about fdroid updating
