### ISSUE TITLE
Bug with colors in latest version

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#194]
Good Morning: 

The latest version on a Samsung S9 + the main screen the text is oversized. And the settings wheel is not visible. Along with the menu that comes out to clean or cancel. I upload screenshots to show how it looks:

https://ibb.co/1JRR1Yv
https://ibb.co/CsJCxmc

If you look at the bottom right the sprocket is not visible. And in the menu that comes out when you give clean the text either. 

Which in the previous version did not happen. It was better that text to clean or not and the sprocket. In a green color like the lte cleaner icon or in white.

 A hug

**Comment by TheRedSpy15** [comment]
Ok yah this will be fixed, probably has to do with the newer version of constraint layout which seems to be buggy

**Comment by gallegonovato** [comment]
good afternoon @TheRedSpy15 

Thank you very much for your answer and help. I also looked at several other mobiles. Nexus 6p, Htc, Samsung and the status letters: unoccupied. They take the whole circle where the % appears I mean https://ibb.co/BTWWLH5. On the other hand, in these phones the icons come out well. Less on the s9 +. 

A hug and thanks for your help and time

**Comment by gallegonovato** [comment]
Good evening @TheRedSpy15

What I did notice in the latest version. That if in settings, you have Auto Whitelist checked. Every time you scan and clean. Or already directly you have clean.

It fills the whitelist. With the same addresses or paths of the files to keep. Repeating the paths and so on again and again. And always the same with each scan and clean. 

In the previous version this did not happen. I imagine that this is done in case there are new changes or new applications and others on the mobile. But it always fills the whitelist with the same thing. And in the previous version also checked the changes and so on but did not do this in the whitelist.

A hug and thanks for your time

**Comment by TheRedSpy15** [comment]
I'm trying out a new testing setup. I just want to confirm, the images are from an S9 in Spanish? Also, have you modified any system settings to change the font?

**Comment by TheRedSpy15** [comment]
I will have a fix for this tomorrow. I figured out the solution. Going to convert the MainActivity layout to use a LinearLayout instead of a ConstraintLayout. Waaay less buggy

**Comment by gallegonovato** [comment]
Good morning @ TheRedSpy15 

Glad you found an easy solution. Because you notice the change the change of the colors. Yesterday I skipped the update of fdroid from Lte. For various teams and the sprocket looks pure black but very clear (hardly seen). And the pop-up menus also don't know what it says underneath. What I do notice is that when you give it to clean, and the menu comes out to clean or not. It puts in Spanish: limpio . 

It would not be better to put:

limpiar
¿limpio?
limpieza 
aceptar

A hug and a thousand thanks for your help and a thousand thanks for your help and time

**Comment by TheRedSpy15** [comment]
I should also mention the color issue is related to the dark mode/setting on the phone. I have a fix for that too, since the app is already dark, I'm going to make it ignore that setting

**Comment by gallegonovato** [comment]
Good morning @ TheRedSpy15

 I am glad that you have found the problem and the solution. But I don't know if it will be the color palette also of Lte.

 Since for example where I work. Everyone uses their app. And for example in a Htc Desire 820; which has no dark mode. The same thing happens. And as in other terminals, without having this mode active. 

A hug and a thousand thanks for your time

**Comment by TheRedSpy15** [comment]
I will be publishing the update in a couple hours, and should be on the playstore within 24 hours. Please let me know if it addresses your issue

**Comment by gallegonovato** [comment]
good afternoon @TheRedSpy15

 THANK YOU FOR SOLVING THE PROBLEM WITH THE COLORS. AT THE TIME ON THE PHONES I COULD SEE EVERYONE WELL. 

When you have checked: automatic whitelist. It still generates some repeated but not as before, now in five uses I believe in a mobile: https://ibb.co/QjQ4J0n I repeated some but much better than before. 

A hug and a thousand thanks for all your time and help.

**Comment by TheRedSpy15** [comment]
since the colors were fixed, refer to #200 for whitelist bug
