### ISSUE TITLE
Updating from GitHub

### ISSUE THREAD

**Issue by DecoderBox** [TheRedSpy15/LTECleanerFOSS#196]
I want to update LTE Cleaner from GitHub, not from Play Store. How to do it? Do the previous settings which I had adjusted go back to default after updating?

**Comment by TheRedSpy15** [comment]
1. uninstall if you already have the app
2. Check the releases page for all versions
3. here is the latest: https://github.com/TheRedSpy15/LTECleanerFOSS/releases/tag/4.5.0
4. download the .apk file and make sure in developer settings on your phone you allowed third party sources to install apps
5. I'm pretty sure the settings will transfer over as long as you simply uninstall and don't delete all of its data

**Comment by TheRedSpy15** [comment]
I forgot to mention, if you download through Github, the process is not automatic. And you have to manually check for updates
