### ISSUE TITLE
Probably no need to translate the filter strings

### ISSUE THREAD

**Issue by OliverLew** [TheRedSpy15/LTECleanerFOSS#197]
**Is your feature request related to a problem? Please describe.**
I saw the string like `.tmp`, `.Trash`, `.DS_Store`, etc. are being translated in the crowdin project. I am not a dev, but I guess those strings should be just as-is in any language. Although, I haven't seen anywhere they are being used in the app.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheRedSpy15** [comment]
I haven't tested it a whole lot, but I do believe translating them is necessary since those files would likely be in different languages and the filter looks for exact words

**Comment by OliverLew** [comment]
Maybe I haven't seen any occasions where those are translated. If the current machine translations don't do any bad things, I guess it's alright to just leave them.

**Comment by TheRedSpy15** [comment]
I'm going to assume they're ok as is. Since the majority of installs are in non-English speaking countries
