### ISSUE TITLE
Incorrect Russian translation (4.5.0)

### ISSUE THREAD

**Issue by Kommprog** [TheRedSpy15/LTECleanerFOSS#198]
Seems it was made with some automated machine translator, not by native speaker itself.
How can I correct it without having an acc [here](https://crowdin.com/project/lte-cleaner/ru#/master/app/src/main/res)? 

![1 (1)](https://user-images.githubusercontent.com/84424346/132983517-85e99939-b363-4e3d-a811-70de2a2fec7a.png)
![1 (2)](https://user-images.githubusercontent.com/84424346/132983519-57fb4bc2-e4f4-4e36-a49d-6466ac3a58b0.png)
![1 (3)](https://user-images.githubusercontent.com/84424346/132983521-119c5602-c054-4f88-b5ec-b16ce59ff631.png)

**Comment by OliverLew** [comment]
Crowdin supports login with github account

Or maybe change this file and submit a PR:
https://github.com/TheRedSpy15/LTECleanerFOSS/blob/master/app/src/main/res/values-ru-rRU/strings.xml

**Comment by TheRedSpy15** [comment]
> Crowdin supports login with github account
> 
> Or maybe change this file and submit a PR:
> https://github.com/TheRedSpy15/LTECleanerFOSS/blob/master/app/src/main/res/values-ru-rRU/strings.xml

Yes, I used an IBM for all translations

As suggested you can make a pull request

**Comment by Kommprog** [comment]
> 
> 
> > Crowdin supports login with github account
> > Or maybe change this file and submit a PR:
> > https://github.com/TheRedSpy15/LTECleanerFOSS/blob/master/app/src/main/res/values-ru-rRU/strings.xml
> 
> Yes, I used an IBM for all translations
> 
> As suggested you can make a pull request

Corrected it yesterday on the crowdin, thanks.

**Comment by TheRedSpy15** [comment]
Approved! #199
