### ISSUE TITLE
syncthing folder markers are deleted

### ISSUE THREAD

**Issue by sniperle** [TheRedSpy15/LTECleanerFOSS#2]
I use synchting (https://syncthing.net/) and syncthing requires (empty) directories called folder markers named .stfolder to work properly. These folders have been deleted and I had to recreate them for syncing to work again.

Can you please add .stfolder to the internal blacklist or implement a blacklist function where the user can enter files and folders himself.

See: https://docs.syncthing.net/users/faq.html#i-really-hate-the-stfolder-directory-cani-remove-it

Edit: Oh and thank you for creating this SD Maid alternative. :-)

**Comment by TheRedSpy15** [comment]
I will put out a quick patch later that adds it to the whitelist. And in the coming days, add the option for custom whitelist

**Comment by TheRedSpy15** [comment]
Will have the update on the play store within the hour, and on GitHub release sometime tomorrow

**Comment by sniperle** [comment]
Yes, it seems to work. Many Thanks.  :-)

**Comment by TheRedSpy15** [comment]
Glad to hear!

**Comment by sniperle** [comment]
Found another problem with my setup/apps. 
My backup app oandbackup ( https://github.com/jensstein/oandbackup ) creates logs from all backups and uses them to store age e.g.
So the .log files in the folder oandbackups or the complete folder should be white listed.
Looking forward to your custom white list version.  :-)

**Comment by TheRedSpy15** [comment]
Just wanted to keep you updated

The custom whitelists are gonna take about 3-4 days for me to implement

**Comment by sniperle** [comment]
Great, thank you :-)

**Comment by TheRedSpy15** [comment]
After several frustrating hours of hammering my keyboards keys, I figured it out, and now custom whitelist have been added to the latest release!

It is still a work in progress however on the UI side of things

Update 1.8 (custom whitelist) is live on GitHub, and at the time of typing this, being processed on Google Play

**Comment by sniperle** [comment]
Have tested it with my exclusions and it seems to work well. Many Thanks :-)

**Comment by arkinaforlife** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
