### ISSUE TITLE
[Bug] Whitelist

### ISSUE THREAD

**Issue by KanadeTachibana2** [TheRedSpy15/LTECleanerFOSS#200]
**Describe the bug.**

It seems like the whitelist stopped working since version 4.5.0.

**To Reproduce.**

1. Go to 'Whitelist'.
2. Tap on 'Add' new path.
3. Go back and tap on 'Clean'.
4. The whitelist gets ignored and the path still gets cleaned.

**Expected behavior.**

The path shouldn't have been cleaned since it is already in the whitelist.

**Screenshots.**

![](https://user-images.githubusercontent.com/85243826/133888665-1e5dfd39-9675-45ee-a3f6-4a5f3b79262a.png)
![](https://user-images.githubusercontent.com/85243826/133888677-ea4ce3cc-ca0d-4b3b-a403-8a2157194a23.png)

**Smartphone:**

 - Samsung Galaxy A10.
 - Android 9.

**Additional context.**

I'm not 100% sure of this, but I think that what's breaking the whitelist are the brackets surrounding the path.

They weren't there before 4.5.0, and now they get added automatically to the path... causing the whitelist to break (I think).

**Comment by TheRedSpy15** [comment]
I think you're right about the brackets. How the whitelist is stored was changed in 4.5.0. I'll have a fix published in a day or two

**Comment by TheRedSpy15** [comment]
What version are you currently using? 4.5.0 or 4.5.1?

**Comment by KanadeTachibana2** [comment]
it started to happen in 4.5.0, but it still happens in 4.5.1

I waited to create this issue since I was hoping that someone else would mention it, but... yeah, that didn't happen, haha.

**Comment by TheRedSpy15** [comment]
ok it seems only select people are affected by this, I should have a fix in a day or 2

**Comment by gallegonovato** [comment]
good afternoon 

I apologize for my interference. But I don't know if I think I know why he deletes that file from the whitelist

@KanadeTachibana2 in lte settings do you have the checkbox of: Delete .apk files checked?

I comment it @TheRedSpy15 TheRedSpy15 because if this box will look for files. apk on the entire device and erase them. Discriminating or not being on the white list. 

A hug and I hope I have been helpful

**Comment by KanadeTachibana2** [comment]
I'm pretty sure that this is something related to the brackets.

I just did a test in 4.2.1:

![screen_20210920-175555.png](https://user-images.githubusercontent.com/85243826/134075244-3de9fc9a-1184-437c-aafe-fa6c57685056.png)

![screen_20210920-175706.png](https://user-images.githubusercontent.com/85243826/134075270-07c52a7e-18e2-4368-85ab-2ca981eb08e2.png)

**Comment by TheRedSpy15** [comment]
> good afternoon
> 
> I apologize for my interference. But I don't know if I think I know why he deletes that file from the whitelist
> 
> @KanadeTachibana2 in lte settings do you have the checkbox of: Delete .apk files checked?
> 
> I comment it @TheRedSpy15 TheRedSpy15 because if this box will look for files. apk on the entire device and erase them. Discriminating or not being on the white list.
> 
> A hug and I hope I have been helpful

The apk filter works the same way as all the other filters, even when it comes to whitelists. Its supposed to completely ignore any file that has been whitelisted

**Comment by gallegonovato** [comment]
good afternoon @TheRedSpy15 

first of all thanks a million for your work. I think that when changing the language there is a little problem. since I do not know if it is like that or you removed the option to add manually to the white list. 

I comment on it because I do not get the option. upload image https://ibb.co/yq2R0WN

 a hug and a thousand thanks for all your time

**Comment by TheRedSpy15** [comment]
fixed: 52c1b4f527fc9b67d9723b52e19dfbe28b894af6

**Comment by KanadeTachibana2** [comment]
I see that you decided to give it a try to the landscape orientation.

just a tip, you should probably use 'unspecified' instead of 'fullSensor'.

'fullSensor' causes the app to rotate all the time, even when auto-rotation is turned off. 'unspecified' fixes that.

you'll probably notice that strange behaviour, too.

**Comment by TheRedSpy15** [comment]
ah yah that sorta slipped into the commit, I was experimenting with it just before fixing the whitelist
