### ISSUE TITLE
Suggestions for change in the Spanish language

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#203]
good afternoon:

 I would like to propose a change in the application in the Spanish language. Since I tried it on the page and it won't let me do it. the change would be:

https://ibb.co/TkTyVVG
https://ibb.co/pznT1fQ

and on this page:

https://ibb.co/3SPXCLp

Change where it says

Como eliminar carpetas vacías for Borrar y eliminar carpetas vacías 

Suprimir archivos cadaver for Borrar restos de archivos o archivos residuales

Un click en limpio for Activar un click para limpiar ( or Un click para limpiar)

A hug and thanks for your help and time

**Comment by TheRedSpy15** [comment]
Ok I'll add them in manually for the next update

**Comment by TheRedSpy15** [comment]
Spanish translation has been updated
