### ISSUE TITLE
Use ADB to clear cache of other apps

### ISSUE THREAD

**Issue by TheRedSpy15** [TheRedSpy15/LTECleanerFOSS#211]
![Screenshot_2021-10-04-08-45-08](https://user-images.githubusercontent.com/48226312/135787925-cf6299fd-2538-4d65-8e88-00bb3d3e6782.jpeg)

[AppManager](https://github.com/MuntashirAkon/AppManager) has this clear cache option, with ADB permission enabled.

Can we have this feature with `WRITE_SECURE_SETTINGS` permission to LTECleaner?
& make this a paid feature, available only to playstore users. Besides this other options will be free to F-droid users. (no internet permission,no ads in both versions)

_Originally posted by @shuvashish76 in https://github.com/TheRedSpy15/LTECleanerFOSS/discussions/205#discussioncomment-1422574_

**Comment by shuvashish76** [comment]
![Screenshot_2021-10-04-11-01-20](https://user-images.githubusercontent.com/48226312/135799006-5f0302a5-3736-491a-9ac5-ee1caf84e229.jpeg)

Additionally it's possible to clear data/cache of individual apps through AM. Or select multiple apps according to user choice then clear their data/cache.

I feel clearing data, apk backup etc are advanced feature, not required for LTECleaner app.

FRs

- Clear cache of individual or group of user preferred apps.
- Clear cache of all applications with 1 click operation.
