### ISSUE TITLE
Clipboard Cleaner

### ISSUE THREAD

**Issue by shuvashish76** [TheRedSpy15/LTECleanerFOSS#212]
https://github.com/DeweyReed/ClipboardCleaner

![Screenshot_2021-09-17-13-09-10](https://user-images.githubusercontent.com/48226312/135800413-c5529190-8b78-4ab5-a184-3ac03ef898e5.jpeg)
![Screenshot_2021-09-17-13-09-23](https://user-images.githubusercontent.com/48226312/135800442-100b172d-db9f-4aab-afb8-23a46d72f291.jpeg)

FRs

- view clipboard contents
- search & delete individual/multiple clipboard contents
- 1 click clipboard cleaner

I don't expect advanced clipboard functions such as [Clip-Stack](https://github.com/heruoxin/Clip-Stack), [XClipper](https://github.com/KaustubhPatange/XClipper) apps from LTECliner app. Only simple clipboard cleaner options, no advanced edit, import, export etc...

Maybe make it as paid feature as well for Playstore version.

**Comment by TheRedSpy15** [comment]
Ah this is something I attempted when I first made the app and since forgotten about. Will add this to the list!

**Comment by TheRedSpy15** [comment]
Unfortunately there seems to be no way to do this for Samsung devices. This will be put on the back burner for now, don't want a feature that the majority of devices can't use
