### ISSUE TITLE
Widget support

### ISSUE THREAD

**Issue by shuvashish76** [TheRedSpy15/LTECleanerFOSS#213]
Support widget so that instead of going to the app each time users will be able to clean from device home screen.

Maybe a circular transparent - resizable widget just like[ Loop Habit tracker](https://github.com/iSoron/uhabits) app will look great.

![Screenshot_2021-10-04-12-22-19](https://user-images.githubusercontent.com/48226312/135806379-582eae6a-c878-40c0-8ea6-1147fa59021c.jpeg)

Loop Habit tracker has additional option to set widget transparency from settings.

![Screenshot_2021-10-04-12-24-32](https://user-images.githubusercontent.com/48226312/135806535-e6060765-e669-452b-9d93-6cc5ebad6045.jpeg)

**Comment by TheRedSpy15** [comment]
widgets were an idea I scrapped a while ago, it would look kind of ugly and make app size bigger than needs be. I plan on using shortcuts instead which can be used like widgets
