### ISSUE TITLE
changes in the translation from Spanish to English

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#219]
good afternoon @TheRedSpy15 

changes Spanish English translation. 

I think it would be better expressed as I show below, word for word. I don't know what you think.

I put it as it is in the screenshot. And how I think it should be in Spanish each word, paragraph, etc...

configuration pages: https://ibb.co/82X4cx1 https://ibb.co/5sv44mt https://ibb.co/5LYPKVY

Enlaces:

Política de Privacidad
Vea la política de privadad (Enlace externo)

Mire mis aplicaciones or (Mire mis otras aplicaciones)
Trato de tener una nueva, al menos cada semana por lo menos.

Analisis:

Lista blanca automática or Lista automática de permitidos
Detecta carpetas y archivos que deben de ser protegidos automáticamente

Verificación doble
Se repetirá el analisis y  limpieza. Cada vez que se encuentre algun archivo o carpeta. (Límite de 10 analisis)

Filtros:

Habilitar el filtro genèrico
(Analiza y limpia por ejemplo: .temp , .log, registros, etc)

Habilitar el filtro agresivo
(Analiza y limpia en profundidad su dispositivo)

Eliminar carpetas vacias
(Analiza y limpia carpetas vacias)

Eliminar archivos residuales
(Analiza y limpia archivos residuales de su equipo. Por ejemplo tras desinstalar una aplicación)

Eliminar archivos o ficheros de instalación
(Analiza y limpia archivos .apk , usados en la instalación de aplicaciones, programas)

Otros:

Utilizar un solo click para la limpieza y analisis
(No se pedirá confirmación tras presionar el boton de LIMPIAR , en la pantalla principal de la aplicación)

Limpieza diaria
(Se realizará un analisis y limpieza automáticamente, sin que tenga que abrir la aplicación. Puede que no funcione en algunos dispositivos sino esta la aplicación abierta en segundo plano; debido a posibles restricciones OEM)

Limpieza del portapapeles
(Analiza y limpia el portapaples de su dispostivo. No valido para dispositivos de la marca Samsung)

Main application screen: https://ibb.co/LZfYd1B

ANALIZAR

LIMPIAR

LISTA DE PERMITIDOS or LISTA BLANCA

CONFIGURACIÓN

A hug and thanks for your time.

**Comment by TheRedSpy15** [comment]
So sorry, I keep getting distracted

This will be in the next update, hopefully in a few days

**Comment by TheRedSpy15** [comment]
I just noticed that alot contributions have been made on crowdin for translation. I approved all of them and they will be in the next update hopefully tomorrow

**Comment by TheRedSpy15** [comment]
Soooo sorry I've been missing in action here lately. Just an update on this, I had a lot of suggestions put in on crowdin for translation and approved all of them. Play store already has the updated translations, fdroid will be a few days

Hopefully they make it easier to read
