### ISSUE TITLE
Circle around percentage is cropped

### ISSUE THREAD

**Issue by twann4** [TheRedSpy15/LTECleanerFOSS#220]
**Describe the bug**
Not really a bug, but more of an issue with the new UI. The circle around the percentage is cropped on small screens.

**To Reproduce**
1. Just open the app
2. See error

**Expected behavior**
The user should be able to see the whole circle.

**Screenshots**
![Screenshot_20211012-001102_LTE_Cleaner](https://user-images.githubusercontent.com/90352798/136862085-0f1c6dc0-f2fa-444d-b176-b44161233dc2.png)

**Smartphone (please complete the following information):**
 - Device: SM-A310F
 - OS: Android 10
 - Version 4.8.3

**Comment by TheRedSpy15** [comment]
Yahhh the damn circle doesn't want to keep a 1:1 aspect ratio causing this

It really is that simple, but it's taking me a little bit to figure this out and limited with time currently. Will be fixed soon!

**Comment by TheRedSpy15** [comment]
created a temporary fix for this 48a2d0fa883ff9adf4ce7e33477f9688e6b01edc

unfortunately it makes the circle smaller in most situations

**Comment by TheRedSpy15** [comment]
Closing this since the smaller circle size actually fits the look of the app
