### ISSUE TITLE
Give Summary: # of files and folders, combined filesize.

### ISSUE THREAD

**Issue by jgod** [TheRedSpy15/LTECleanerFOSS#24]
Can be at bottom of log output, but should autoscroll to bottom to put into focus.

**Comment by TheRedSpy15** [comment]
Gonna work on adding this, should have an update tonight, if not then tomorrow

**Comment by TheRedSpy15** [comment]
I might be able to squeeze auto scroll into the next update tonight. When I have experimented with it in the past, it led to increased crashes

**Comment by TheRedSpy15** [comment]
I just added auto scroll (not in any released update yet). However, I am planning on overhauling the UI to look waaay nicer, and the list view will get removed
