### ISSUE TITLE
[Bug] Whitelist seems to be broken? (again)

### ISSUE THREAD

**Issue by KanadeTachibana2** [TheRedSpy15/LTECleanerFOSS#244]
.

**Comment by TheRedSpy15** [comment]
My guess is the converting to kotlin process affected this

I should have a fix soon, this is kinda an important feature

**Comment by KanadeTachibana2** [comment]
I just tried the version of the PlayStore, but... it doesn't work there either.

**Comment by KanadeTachibana2** [comment]
the whitelist never worked for me after the 4.5.0 update

**Comment by worthless133** [comment]
I'm getting mixed results here.

if you whitelist a single folder containing a single `.apk` file, it will be successfully whitelisted.

but if you whitelist the entire application data of any app (like I showed above), it will still be ignored in the cleaning process.
