### ISSUE TITLE
Does it work on Android 11?

### ISSUE THREAD

**Issue by angelog0** [TheRedSpy15/LTECleanerFOSS#258]
I installed 4.9.7 from FDroid and I gave it all the permissions it asks but it doesn't seem to clean anything...

**Comment by Tyler887** [comment]
Did you mean to create this in discussions? Questions go there

**Comment by angelog0** [comment]
@Tyler887 wrote:

> Did you mean to create this in discussions? Questions go there

No, unless you say _how_, this application **does nothing**, it doesn't clean anything... on Android 11.

This here is called **BUG**!

**Comment by gallegonovato** [comment]
good afternoon: 

It seems that it does not work very well in Android 11. for example a co-worker. With a Samsung A30s with Android 11. 

The latest version, either from fdroid, github, play store. The application does not look good. It doesn't clean anything.

 The only one that sees the application well is 4.9.4. And when you clean something it's usually the same amount 34 kb. 

But it always shows it as https://github.com/TheRedSpy15/LTECleanerFOSS/issues/257 

A hug

**Comment by varaki** [comment]
Yes, can confirm, doesn't work on android 11.
When opening up the app and pressing clean it just shows a notification about the worker finished with 0 bytes cleaned. If I press the second time it does clean nothing only the progressbar goes through.

**Comment by TheRedSpy15** [comment]
Yes it does work on android 11. That's what I've been using it with for the past year on my personal device.

If it doesn't for the others who commented, this is due for reasons such as bugs or just standard crashes

**Comment by angelog0** [comment]
@TheRedSpy15, so do you think tha since an app does not crash it it working... That's good to know..

**Comment by TheRedSpy15** [comment]
> @angelog0 not what I meant. It runs perfectly fine on every android 11 device I have tested it on. What I'm saying is that for android 11 in general, it works on. But with every version there is going to be outliers
