### ISSUE TITLE
Landing page / Website request:

### ISSUE THREAD

**Issue by aha999** [TheRedSpy15/LTECleanerFOSS#262]
It would be useful to have this project's landing site / website, so any future news articles can link to it and the website would make a better visual representation of the project that could attract more users, developers and contributors.

A simple and free option is via [Github Pages](https://pages.github.com/), that a lot of github open source projects are using, which Github hosts for any repo on their website.

> Hosted directly from your GitHub repository. Just edit, push, and your changes are live.
> No databases are needed to be set up and no servers to configure

Repositories that use github pages: [Examples](https://github.com/collections/github-pages-examples)

Interesting article: [Link](https://www.toptal.com/github/unlimited-scale-web-hosting-github-pages-cloudflare)

> Consider [Jekyll](https://jekyllrb.com/). You give it [Liquid](https://jekyllrb.com/docs/liquid/) templates and Markdown content
> Free Jekyll templates: https://jekyllthemes.io/free

**Comment by jixt3r** [comment]
I can try programming if you already have the design

**Comment by TheRedSpy15** [comment]
already have one: https://theredspy15.github.io/LTECleanerFOSS/
