### ISSUE TITLE
will there be a new version?

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#274]
Good afternoon:

I wanted to ask a question, if I may.

Will there be any Lte update in the future, containing bug fixes?

Best regards and thanks for your time

**Comment by TheRedSpy15** [comment]
Yes hopefully within a week or so. I realize I've been MIA for a while now. I'm currently in the process of building a startup software company, so pretty much anytime I have time to write some code, it's related to that. Thus putting LTE Cleaner on the backburner

But I should be at a point soon to start releasing updates again very soon

**Comment by gallegonovato** [comment]
Good afternoon @TheRedSpy15

Thank you very much for your response and time.

We look forward to the new update when you can. To continue using without problems your great application.

A hug and thanks for your time

**Comment by gallegonovato** [comment]
Good afternoon @TheRedSpy15 

I wanted to report a strange thing that happened to a colleague of mine with D4rK Cleaner 6.1_r5.

It turns out that in the report he had deleted some screenshots. A zip file (I had in downloads) and ubos .apk (also in downloads).

But I didn't remove them, they were still there.

Nor does it say that it deletes the recent folder.

Thank you very much for your time and help and sorry for the inconvenience.
