### ISSUE TITLE
[question]  privacy policy

### ISSUE THREAD

**Issue by gbdomubpkm** [TheRedSpy15/LTECleanerFOSS#276]
Hello.

Thank you for your work now and in the future.
I may need to test your very useful apk (I'm still on Android 10 APSP by necessity so it should work), but I'm hesitant, wondering what privacy is observed in the total scan of a smartphone's data, which is no small thing! There is indeed a privacy policy included in your program, but if you could clarify it for me in your words. In fact, whatever the program (apk) so not only yours, I like when any analysis/scan remains confined to the phone, and if I conceive that logs (annomized and devoid of personal data for this apk ?) can be transmitted (to you only here ? ) to analyze bugs and make the app progress, that it be by choice of the user, and not that it be imposed therefore without choice (some programs show the logs that can be copied and sent to the designer, others have a switch to give at a certain time its agreement to transmit or not...).
I hope that my remarks will be useful to you.

Best regards

**Comment by TheRedSpy15** [comment]
This is different from where you download from. The playstore varient collects some basic device hardware info which allows for me to get a better understanding of which devices (and especially languages in my case) to focus on supporting. There is also crashlytics, whenever an exeception (error) occurs, the app freezes, or crashes. I get a log of the crash (including hardware info)

From github or fdroid nothing is ever collected. Even if the app crashes

**Comment by gbdomubpkm** [comment]
> And since admob is also used on the playstore variant, some advertising info is collected outside of my control. Unless you block it using blokada or something

Sorry, as english isn't my first langage, what do you mean by 'playstore variant' ? You confirm nothing at all on F-DROID ?

**Comment by gallegonovato** [comment]
Good afternoon @gbdomubpkm

Some time ago @TheRedSpy15 asked https://github.com/TheRedSpy15/LTECleanerFOSS/discussions/205 osea made a free version with ads for the play store. And then created an unlocker at a price (ie to remove ads and add some stuff. I mean pro on Google Play). And it is still on Fdroid https://f-droid.org/es/packages/theredspy15.ltecleanerfoss/ and on his github without ads. That is Pro version.

Hence the Google Play version has to follow Google's rules for developers and others. And what the developer tells you

A hug

In Spanish:

Buenas tardes @gbdomubpkm

Hace tiempo @TheRedSpy15 pregunto https://github.com/TheRedSpy15/LTECleanerFOSS/discussions/205 osea que hizo una version gratuita con anuncios para la play store. Y luego creo un desbloqueador a un precio (es decir para quitar los anuncios y añadir unas cosas. Es decir pro en la Google Play). Y sigue en Fdroid https://f-droid.org/es/packages/theredspy15.ltecleanerfoss/ y en su github sin anuncios. Osea version Pro.

De ahi de que la version de Google Play, tenga que seguir lo que rige Google para los desarrolladores y demas. Y lo que te comenta el desarrollador.

Un abrazo
