### ISSUE TITLE
Add Screenshots on F-Droid

### ISSUE THREAD

**Issue by mueller-ma** [TheRedSpy15/LTECleanerFOSS#28]
I've seen this app on F-Droid, but it lacks screenshots, changelog and a translatable description there. It's pretty easy for you to add these information. Please have a look at [this example](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android) or at the [F-Droid docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) or [fastlane docs](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots).
After you have commited these files to your repo and tagged a new version, you need to remove the `Description` and `Summary` from the metadata file in the [F-Droid Data repo](https://gitlab.com/fdroid/fdroiddata).

**Comment by Jojopogo22** [comment]
Also, the 'too' in the app description should be 'to' instead.

**Comment by TheRedSpy15** [comment]
I will being working on this today or tomorrow

Been a little busy with another project

**Comment by TheRedSpy15** [comment]
Update: I might be able to get screenshots up later today. I've been looking at how to do it a few times a week, and its rather confusing

**Comment by TheRedSpy15** [comment]
use #168
