### ISSUE TITLE
Logo Proposal.

### ISSUE THREAD

**Issue by mendezand** [TheRedSpy15/LTECleanerFOSS#3]
Hello, how are you?

I am willing to create a new logo for LTE Cleaner. If you want a new design for your application, do not hesitate to contact me.

Greetings.

**Comment by TheRedSpy15** [comment]
Hello!

I would love a new logo, the current one is very lacking

As long as I don't have to pay, go ahead and make one, it would be very much appreciated!

**Comment by mendezand** [comment]
I will be working on that.
Do you have something in mind or a specific detail that you want me to add to the logo?

**Comment by TheRedSpy15** [comment]
Nothing in particular, however I would love it if you could incorporate these two colors somehow:
#292929
#53b440

**Comment by mendezand** [comment]
Hi again.
I have done this work.
You can ask me for any change you want. I hope you like it.

Greetings.
![preview](https://user-images.githubusercontent.com/38763253/42001756-004ce5b8-7a33-11e8-9784-5528fed6b7e8.png)

**Comment by TheRedSpy15** [comment]
Awesome!!! Looks great!

Do you have them as separate files? Also, could you email me them at hjadar15@protonmail.com

**Comment by mendezand** [comment]
I share with you the editable files. You can download them [here](https://drive.google.com/drive/folders/1fCI1vIK3sbIhcu7LnVyEazOu_py8_PSd?usp=sharing)

**Comment by TheRedSpy15** [comment]
Thank you so much for doing this! You are very talented!

**Comment by mendezand** [comment]
So glad you like it. I'm attentive if you need help in logos of other applications.

Best regards.
