### ISSUE TITLE
Unable to remove pre-added item from whitelist

### ISSUE THREAD

**Issue by Sarkasper** [TheRedSpy15/LTECleanerFOSS#35]
Description:
---

It would be nice to remove some of the items already on the whitelist

Device info:
---
<table>
<tr><td>App version</td><td>3.1.0</td></tr>
<tr><td>App version code</td><td>18</td></tr>
<tr><td>Android build version</td><td>43402c2f68</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>lineage_kuntao-userdebug 8.1.0 OPM7.181105.004 43402c2f68 dev-keys</td></tr>
<tr><td>Device brand</td><td>Lenovo</td></tr>
<tr><td>Device manufacturer</td><td>LENOVO</td></tr>
<tr><td>Device name</td><td>P2a42</td></tr>
<tr><td>Device model</td><td>Lenovo P2a42</td></tr>
<tr><td>Device product name</td><td>lineage_kuntao</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
This has already been mentioned #21

**Comment by TheRedSpy15** [comment]
This has been planned for the next release

(Excluding the one coming out tonight)

**Comment by TheRedSpy15** [comment]
The default whitelist have been removed, with the option to re-add them
