### ISSUE TITLE
F-Droid version is not updated

### ISSUE THREAD

**Issue by Hellohat** [TheRedSpy15/LTECleanerFOSS#37]
This app on F-Droid repos is still 3.1.0. 
I read somewhere that F-Droid make an update automatically when the version code in the build.gradle is changed. If the app development is finish, can you change it?
Thank you

**Comment by TheRedSpy15** [comment]
I seem to have forgotten to change the version code. Unless I just didn't  commit it yet

Expect an update real soon!

**Comment by Ud4ba** [comment]
Well still we havent got the update .. this issue is one month old..

**Comment by TheRedSpy15** [comment]
@Us4ba yah, unfortunately we have to wait for the next cycle

If it doesn't get updated it a few days I will have no choice but to contact FDroid maintainers

**Comment by Ud4ba** [comment]
still.

**Comment by Ud4ba** [comment]
I dont know if this is sad or even funny ... the update wont come .. Bye bye Lte cleaner.

**Comment by TheRedSpy15** [comment]
Update: It seems to be a GitHub issue if I understand correctly. I'm publishing a major update tonight, hopefully I figured out a way around it. FDroid sadly is gonna miss out on the last update

**Comment by TheRedSpy15** [comment]
As of today of posting this reply: FDroid now has the latest version (3.6.2)
