### ISSUE TITLE
All non English languages need added translations

### ISSUE THREAD

**Issue by TheRedSpy15** [TheRedSpy15/LTECleanerFOSS#39]
Due to the last few updates, there are a few added (and modified) strings that need to be translated in all non English languages

It is **highly** recommended to use Stringlate from F-Droid to help translate the app

**Comment by Asbesbopispa** [comment]
I translated these strings in Italian with Stringlate, let me know if they're alright. 
[strings.zip](https://github.com/TheRedSpy15/LTECleanerFOSS/files/3080107/strings.zip)

**Comment by TheRedSpy15** [comment]
@Asbesbopispa Perfect! Thank you!

**Comment by shachi120** [comment]
Hi, I have added support for Hindi (hi-IN) [here]. let me know something more require in this pull request. :) (https://github.com/TheRedSpy15/LTECleanerFOSS/pull/75)

**Comment by declare2006** [comment]
Hi all, I can translate them into Chinese language. Where can I find the original strings? Thanks!

**Comment by TheRedSpy15** [comment]
@declare2006

I recommend downloading an app called stringlate from f-droid to modify strings

**Comment by TheRedSpy15** [comment]
**UPDATE**

I will be holding off on updates until more translations are added/improved. This seems to be the current most requested thing and source of many complaints

**Comment by WaldiSt** [comment]
Zaktualizuj tłumaczenie na język polski
[string.zip](https://github.com/TheRedSpy15/LTECleanerFOSS/files/4892527/string.zip)

**Comment by WaldiSt** [comment]
Please update translation to Polish language
[string.zip](https://github.com/TheRedSpy15/LTECleanerFOSS/files/4892535/string.zip)

**Comment by Asbesbopispa** [comment]
@TheRedSpy15 I updated the Italian translation
[strings.zip](https://github.com/TheRedSpy15/LTECleanerFOSS/files/4893751/strings.zip)

**Comment by MaciejPrzekwas** [comment]
> 
> 
> Please update translation to Polish language
> [string.zip](https://github.com/TheRedSpy15/LTECleanerFOSS/files/4892535/string.zip)

Hello,
I can help with Polish

**Comment by TheRedSpy15** [comment]
Most of the top languages are not being translated thanks to IBM's watson
