### ISSUE TITLE
AliExpress logs

### ISSUE THREAD

**Issue by abvgeej** [TheRedSpy15/LTECleanerFOSS#40]
Description:
---

storage/emulated/0/Android/data/com.alibaba.aliexpresshd/files/logs

**Comment by abvgeej** [comment]
nevermind, but the bug reporting in-app is very confusing
I wanted to propose one more path which contains potentially useless files

**Comment by TheRedSpy15** [comment]
I'm assuming the path in the description is the one you're talking about

If so, I will take a look at the code tomorrow and see why it wasn't removed

**Comment by TheRedSpy15** [comment]
Hello,
After the latest update (3.6.2), is path being cleaned?

**Comment by abvgeej** [comment]
Sorry for the incomprehensible description, but this is how I initially understood the built-in error message form.
In fact, my request is a blacklist function with a list of potentially useless paths.

**Comment by abvgeej** [comment]
No

**Comment by abvgeej** [comment]
Yes
