### ISSUE TITLE
JUnit Testing

### ISSUE THREAD

**Issue by TheRedSpy15** [TheRedSpy15/LTECleanerFOSS#45]
As a simple and easy way to contribute, and because the project does need testing

**Comment by M1Aston** [comment]
Aggressive and generic filters are enabled.
I think HERE WeGo installation (offline maps) gets damaged by cleaning. A huge amount of files were deleted in a single run. That can't just be junk files, temporary files or things like that.
https://play.google.com/store/apps/details?id=com.here.app.maps&hl=en

**Comment by TheRedSpy15** [comment]
@M1Aston

I will be looking into this. However, please create a new issue for this

**Comment by rtsketo** [comment]
I'd like to contribute to this, if it's still open.
I've been looking into the code, and to my understanding it would be easier to test the methods that provide the main functionality of the app (like getListFiles) if they are independent of the MainActivity class.
Is refactoring acceptable? If so, should it be in a separate PR?

**Comment by TheRedSpy15** [comment]
@rtsketo this is still open, refactoring is perfectly fine. Also, a separate pr would be preferable
