### ISSUE TITLE
Whitelist text is black on black

### ISSUE THREAD

**Issue by TacoTheDank** [TheRedSpy15/LTECleanerFOSS#46]
Doesn't seem to be device specific, so info not really needed.

![Screenshot_20190316-192020_LTE Cleaner](https://user-images.githubusercontent.com/32376686/54482913-1d0ca780-4821-11e9-92fd-07aa5cbc7b68.jpg)

**Comment by TheRedSpy15** [comment]
I will changing that in a little bit

But it will have to wait until the next update coming in a few days

**Comment by TacoTheDank** [comment]
Ok, thanks :)
