### ISSUE TITLE
Filters description

### ISSUE THREAD

**Issue by abvgdeyoj** [TheRedSpy15/LTECleanerFOSS#47]
There is no information provided in the app on what the filters do.
Only way right now is to see the source, which has certain drawbacks.

**Comment by TheRedSpy15** [comment]
I will be working on a button that will open a pop up listing the current filters in use

**Comment by username-is-not** [comment]
> There is no information provided in the app on what the filters do.

What filters, Settings, Enable aggressive filter - where it's clearly stated: "Too much to list here"? That information?.. I suppose if English wasn't your first language. Aanyway 😉🙂

**Comment by TheRedSpy15** [comment]
my plan for this it to allow the user to long press on the aggressive filter button, to display a popup listing each keyword it adds to the filter

**Comment by TheRedSpy15** [comment]
added 0dcd82f7d57da71ab56ca617efee532c25b97ea1

even better solution than I originally planned
