### ISSUE TITLE
Spotify / Blacklist

### ISSUE THREAD

**Issue by zlyfer** [TheRedSpy15/LTECleanerFOSS#48]
Would be nice if the cache and storage of Spotify would be blacklisted or if a blacklist feature would be added in general.

**Comment by TheRedSpy15** [comment]
I will be adding a custom blacklist feature at some point (not this coming release)

I also just tested, the spotify cache is already cleaned when the aggressive filter is enabled

**Comment by zlyfer** [comment]
Yea that's right but it also cleans the Spotify storage which is stupid since it contains the downloaded music from Spotify.
I tested it with generic filter, aggressive filter, auto whitelist, a clean whitelist and a whitelist with filled recommended entries in every possible combination and each seem to randomly detect the storage to clean. I disabled quick clean to analyse and it sometimes shows the Spotify storage to clean and sometimes doesn't.

**Comment by TheRedSpy15** [comment]
hmm.... I'll look into when I get back from visiting family. 

In the mean time; have you manually whitelisted the folder?

**Comment by zlyfer** [comment]
Nevermind, I'm an complete idiot. I somehow thought the whitelist makes folders to definitely be clean and the (upcoming?) blacklist is the opposite. I guess this makes sense now but I think it should be more clear since a whitelist mostly adds things (to a specific task list) instead of removing.
Nevertheless the analyser still shows different results even when on the same settings.
