### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by BloodReleasesPain** [TheRedSpy15/LTECleanerFOSS#50]
Description:
---

Can you add a feature for duplicate files? Thanks!

Device info:
---
<table>
<tr><td>App version</td><td>4.0.9</td></tr>
<tr><td>App version code</td><td>35</td></tr>
<tr><td>Android build version</td><td>G935TUVS9CSC1</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.G935TUVS9CSC1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hero2qltetmo</td></tr>
<tr><td>Device model</td><td>SM-G935T</td></tr>
<tr><td>Device product name</td><td>hero2qltetmo</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
On the todo list 👍

**Comment by TheRedSpy15** [comment]
follow this issue here #165
