### ISSUE TITLE
The app will have the cache cleaner function?

### ISSUE THREAD

**Issue by Relwi** [TheRedSpy15/LTECleanerFOSS#51]
Will have the cache cleaner function for rooted devices in the future? Sry for my English

**Comment by TheRedSpy15** [comment]
As I don't have a rooted device for testing, and don't wanna brick a $1k phone. I unfortunately can't implement it.

Sorry

**Comment by Relwi** [comment]
Okay, no problem

**Comment by TheRedSpy15** [comment]
I would like to add: I am not ruling this out. I just can't implement it at this time
