### ISSUE TITLE
LTE Cleaner 4.0.9 stays Fozzen 

### ISSUE THREAD

**Issue by Freyaman** [TheRedSpy15/LTECleanerFOSS#52]
Open LTE Cleaner 4.0.9 got 0% and dose nothing stay that way all day.  I Have a Moto Z3 with android pie/9 in 32GB  256 sd  8cord CPU 64ram.

![Screenshot_20190607-162826](https://user-images.githubusercontent.com/51493548/59133704-d5d91300-8946-11e9-88da-043ad58f8cbd.png)

**Comment by TheRedSpy15** [comment]
Hmm.... I will look into this

**Comment by puppykickr** [comment]
I have the same issue on a Poblano VLE 8.1.0

**Comment by TheRedSpy15** [comment]
It looks like you have access accessibility settings enabled for android. Try turning those off

**Comment by puppykickr** [comment]
The recent update completely broke the app.
It does nothing, regardless of the settings.

https://drive.google.com/folderview?id=18CXHWF-ULlhwaQNspdBOzLh7cndFjv5W

**Comment by puppykickr** [comment]
Well, there are a few, but they are necessary.

In fact, the odds of remembering to turn them back on before theyare needed
is slim.

If this is a requirement, then I will just use a previous version or a
different app.

Grant Ryan Swan
(puppykicker)

**Comment by TheRedSpy15** [comment]
I am making fixing the UI top priority before I leave a trip in a few days. I should hopefully have it fixed before then

**Comment by puppykickr** [comment]
Sounds good, thanks!

Grant Ryan Swan
(puppykicker)

**Comment by Freyaman** [comment]
Works Great Now, Thank You.
