### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Pablo-Balaudo** [TheRedSpy15/LTECleanerFOSS#54]
When I click on the Privacy Policy the app crashes.
When I tried to report the problem via the app, it gives me an error "Unable to send report: Invalid access token. Please contact the app developer".

App version: 4.0.6
App version code: 32
Device: Motorola Moto G (4)
Android version: 7.0
Android SDK version: 24

**Comment by TheRedSpy15** [comment]
Fixed! The button was never given a url

Fix should be released in a couple days
