### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by ghost** [TheRedSpy15/LTECleanerFOSS#55]
Description:
---

Allow us to remove individual filters from the Whitelist.

Device info:
---
<table>
<tr><td>App version</td><td>4.0.6</td></tr>
<tr><td>App version code</td><td>32</td></tr>
<tr><td>Android build version</td><td>4</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>OCPS27.91-150-4</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>hannah</td></tr>
<tr><td>Device model</td><td>moto e5 plus</td></tr>
<tr><td>Device product name</td><td>hannah_t</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
Already on the to-do list

**Comment by marvinamari** [comment]
I would like to work on this issue if still available, I've worked with Java but not android so I may need a little help getting started but I am more than happy to help.

**Comment by TheRedSpy15** [comment]
@marvinamari

This is still very much available. I just don't have time to work on it.

It would be greatly appreciated if you worked on it

**Comment by TheRedSpy15** [comment]
Added f75b15782a1988c49fe59b3c15b50181a957e0e1

Along with an entirely improved look to the whitelist screen
