### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by Neurasthenic** [TheRedSpy15/LTECleanerFOSS#56]
Description:
---

It would be nice to have a bright theme

Device info:
---
<table>
<tr><td>App version</td><td>4.0.6</td></tr>
<tr><td>App version code</td><td>32</td></tr>
<tr><td>Android build version</td><td>15.2016.1902.340-20190216</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>OPM1.WW_Phone-15.2016.1902.340-20190216</td></tr>
<tr><td>Device brand</td><td>asus</td></tr>
<tr><td>Device manufacturer</td><td>asus</td></tr>
<tr><td>Device name</td><td>ASUS_X00T_6</td></tr>
<tr><td>Device model</td><td>ZB602KL</td></tr>
<tr><td>Device product name</td><td>RU_X00TD</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
Hello!

Unless someone makes a pull request. I do not plan on adding a light theme. I personally dislike them.

However, I won't stop someone from contributing one

**Comment by RenatoViana01** [comment]
Should I build one?

**Comment by TheRedSpy15** [comment]
@RenatoViana01 

Go ahead! Just make sure to include an option in the settings to switch between light and dark

**Comment by aryaanlambe** [comment]
Hello,
Is this issue still up for grabs? I'd like to work on it.

**Comment by TheRedSpy15** [comment]
@aryaanlambe yes

**Comment by aryaanlambe** [comment]
Great! Is there a deadline you're expecting?

**Comment by TheRedSpy15** [comment]
@aryaanlambe Nope! Feel free to work at your own pace

**Comment by aryaanlambe** [comment]
Okay. I'll get working on it

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment]
I would like to suggest following the system default theme that is available from Android 10 (API level 29):
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by TheRedSpy15** [comment]
update on this suggest, with Android's day/night theme styles, I will be adding this for the next major update. It will by default follow system settings, but have a setting to manually change it

**Comment by TheRedSpy15** [comment]
Added fe167a3baedd3777b8e2dc71ec5664a37967a0f8
