### ISSUE TITLE
Use regex for file detection

### ISSUE THREAD

**Issue by rtsketo** [TheRedSpy15/LTECleanerFOSS#65]
There is an issue as far as I can tell, not sure if it's intended to work that way.
Any file that contains a specific word to be passing the filter. For example the app will delete a file named firemaking_logs.png while it's clearly an image file and not a log file. This is also happens with directories as the filter searches for specific words in the whole path of a file, which results in all the files to be deleted in a directory for example named Logistics.

My suggestion is that the filters should be more specific (use of regex).

**Comment by TheRedSpy15** [comment]
Actually, that's a good idea!

I made this project before I learned regex, so I would never have thought of that

**Comment by rtsketo** [comment]
I'll start working on it, ok?
