### ISSUE TITLE
Should the app exit on no permission given?

### ISSUE THREAD

**Issue by RenatoViana01** [TheRedSpy15/LTECleanerFOSS#71]
Should the app exit on no permission given?

It's very easy to implement a fragment that just tells the user to go to settings -> give app permission. Should I do it and make a pull request?

**Comment by TheRedSpy15** [comment]
Yes,

I kinda got a little lazy one day and decided to just close the app. Knowing this isn't the greatest idea

It would be most appreciated if you would make a pull request

**Comment by RenatoViana01** [comment]
Just made a pull request :)

**Comment by TheRedSpy15** [comment]
Merged!

Thank you!
