### ISSUE TITLE
Upload to fdroid?

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#89]
Good afternoon:

I thank you for all your effort and for this new version. 

I wanted to ask you if you are going to upload it to fdroid and when.

A hug

**Comment by TheRedSpy15** [comment]
Hello!

I unfortunately don't have any control to when F-Droid will release the update. It should be on there within the week. If not then something went wrong and I have to look into it.

But you can download the update from GitHub releases directly (where F-Droid pulls from) or from Google Play
