### ISSUE TITLE
App cache

### ISSUE THREAD

**Issue by kavillock** [TheRedSpy15/LTECleanerFOSS#9]
Description:
---

It's possible to add app cache cleaning with this app? 

Device info:
---
<table>
<tr><td>App version</td><td>2.1</td></tr>
<tr><td>App version code</td><td>8</td></tr>
<tr><td>Android build version</td><td>1506071856</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>Hammer_Active_V1.06_20170922</td></tr>
<tr><td>Device brand</td><td>myPhone</td></tr>
<tr><td>Device manufacturer</td><td>myPhone</td></tr>
<tr><td>Device name</td><td>HammerActive</td></tr>
<tr><td>Device model</td><td>Hammer Active</td></tr>
<tr><td>Device product name</td><td>Hammer_Active</td></tr>
<tr><td>Device hardware name</td><td>mt6580</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by dimqua** [comment]
According to the description:

>Android API 23+ (Marshmallow) no longer allows apps to clean other app's caches, thus the claim of cleaners clearing them is completely false.
