### ISSUE TITLE
Widget and auto cleaning for LTE cleaner

### ISSUE THREAD

**Issue by Nig616** [TheRedSpy15/LTECleanerFOSS#90]
Description:
---

Suggestion 1:
Could you add a setting for auto cleaning 
Make it so you can have LTE cleaner clean at certain times (choose what time of day and day of the week)
And have another setting for having LTE cleaner clean every minute in the background.
Suggestion 2:
Add a small 1x1 widget that starts LTE cleaner
And another widget for starting auto cleaning

Thank you for making this app it's the best cleaner that's free, has no ads and no malware

Device info:
---
<table>
<tr><td>App version</td><td>4.0.6</td></tr>
<tr><td>App version code</td><td>32</td></tr>
<tr><td>Android build version</td><td>A505FNXXU3ASL6</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.A505FNXXU3ASL6</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a50</td></tr>
<tr><td>Device model</td><td>SM-A505FN</td></tr>
<tr><td>Device product name</td><td>a50eea</td></tr>
<tr><td>Device hardware name</td><td>exynos9610</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
1) Already planned for the next release. However every minute would be extremely taxing on the device's performance and battery

2) already planned

**Comment by TheRedSpy15** [comment]
1: #49 

2: idea sorta has been cancelled. Feed back from multiple users want to keep app small. Adding widgets would simply bloat the app and aren't needed with automatic cleaning anyways
