### ISSUE TITLE
General usability suggestions

### ISSUE THREAD

**Issue by PacoBell** [TheRedSpy15/LTECleanerFOSS#98]
**Is your feature request related to a problem? Please describe.**
I applaud what you're trying to do here and it's definitely got potential, but just dumping a list of files on the user and expecting them to make actionable decisions based on just that is asking too much. You might as well not show the list at all. It's so overwhelming. 

**Describe the solution you'd like**
Rather, it would be better if you could analyze the list by app and show the storage consumption of the temporary files for each of them (preferably, sortable). Then, if the user feels compelled, expand the list of discovered files. Also, when a list gets really long, it would be helpful if you could provide a quick scroll handle that can be dragged around. Finally, the current operation is a one-or-nothing affair. I'd like to be able to select which apps for which I want to clear the cache.

**Comment by TheRedSpy15** [comment]
Hello! I plan on removing the log in the future. And replacing it with a summary of how of what types of files are found

**Comment by TheRedSpy15** [comment]
Closing this due to the entire layout being updated to a more modern one
